
---
type: yml
auth:
  sign_key: "Hmdsfksdf"

http_server:
  port: 8080

mysql:
  host: localhost
  port: 3308
  dbname: gameappDB
  username: Hamed
  password:  hmah8013



redis:
  port: 6380
  host: localhost
  db: 0
  password: ""

matchingservice:
  waiting_timeout: "2m"