
---
type: yml
auth:
  sign_key: "Hmdsfksdf"

http_server:
  port: 8080

presence_service:
  presence_expire_time: "60m"
  presence_prefix: "presence"

redis_matching:
  waiting_list: "waiting_users"


mysql:
  host: localhost
  port: 3308
  dbname: gameappDB
  username: Hamed
  password:  hmah8013

scheduler:
  match_waited_users_internal_in_seconds: 10

redis:
  port: 6380
  host: localhost
  db: 0
  password: ""

matchingservice:
  waiting_timeout: "2m"