
---
type: yml
auth:
  sign_key: "Hmdsfksdf"

mysql:
  host: localhost
  port: 3308
  db_name: game_db


redis:
  port: 6380
  host: localhost
  db: 0
  password: ""

matchingservice:
  waiting_timeout: "2m"